apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:{{ include "oxide-ccm.fullName" . }}
  labels:
    {{- include "oxide-ccm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:{{ include "oxide-ccm.fullName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "oxide-ccm.fullName" . }}
  namespace: {{ .Release.Namespace }}
