apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oxide-ccm.fullName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oxide-ccm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oxide-ccm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "oxide-ccm.selectorLabels" . | nindent 8 }}
    spec:
      dnsPolicy: Default
      hostNetwork: true
      serviceAccountName: {{ include "oxide-ccm.fullName" . }}
      priorityClassName: system-cluster-critical
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "oxide-ccm.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - "/usr/bin/oxide-cloud-controller-manager"
          - "--cloud-provider=oxide"
          {{- range .Values.extraArgs }}
          - {{ . | quote }}
          {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
          - name: OXIDE_HOST
            valueFrom:
              secretKeyRef:
                name: {{ include "oxide-ccm.fullName" . }}
                key: oxide-host
          - name: OXIDE_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "oxide-ccm.fullName" . }}
                key: oxide-token
          - name: OXIDE_PROJECT
            valueFrom:
              secretKeyRef:
                name: {{ include "oxide-ccm.fullName" . }}
                key: oxide-project
