---
on:
  pull_request: {}

name: Manifest

jobs:
  manifest:
    name: Check Generated Manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Generate Manifest
        run: make manifest

      - name: Check for Changes
        run: |
          if ! git diff --exit-code; then
            echo "::error::Generated code out of date. Run 'make manifest' and commit the result."
            exit 1
          fi
